### ISSUE TITLE
question:  Why move to `yay`

### ISSUE THREAD

**Issue by appetrosyan** [dan-online/parrot#191]
### Description

This is rather interesting.

The program states that it's based on `paru`, which makes sense given the tech stack. And then... the `README.md` states that the program is planning to move to `yay`, a Go program, and the installation instructions assume you have `yay` installed? 

What gives?

**Comment by dan-online** [comment]
Hey @appetrosyan, for why I added moving to `yay` in the todo, I noticed that paru rarely receives updates and therefore I thought about moving to yay in the future. As for the README, I could probably update it to use paru however I believe the app auto-downloads paru itself so there's neither are really a requirement

**Comment by appetrosyan** [comment]
thank you
